table FluxoCaixaCompleto
	lineageTag: ff5324d3-a937-42c3-9937-cbfb28dbb7a2

	column DataOriginal
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c9bd6d58-a100-4b73-80b6-c33fd2469dd7
		summarizeBy: none
		sourceColumn: DataOriginal

		variation Variation
			isDefault
			relationship: 41ae07d4-3da0-42c7-b37c-cdb5ca308a26
			defaultHierarchy: LocalDateTable_e03502aa-f7f1-4afb-8358-472d37202c8a.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column DataCompetencia
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: cde838fb-1cba-44e1-8508-49e9ffe327db
		summarizeBy: none
		sourceColumn: DataCompetencia

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Tipo
		dataType: string
		lineageTag: ab3c92d5-75d3-450d-9b1c-02584b2dfb46
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Metodo
		dataType: string
		lineageTag: d868121b-f8fd-4d41-931b-7359986635d4
		summarizeBy: none
		sourceColumn: Metodo

		annotation SummarizationSetBy = Automatic

	column Conta_Cartao
		dataType: string
		lineageTag: 61ab1ea8-a0c4-4896-ac8b-d4eddc47effd
		summarizeBy: none
		sourceColumn: Conta_Cartao

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 9fc392fe-48c5-45b4-9993-643ae08f54d2
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Descricao
		dataType: string
		lineageTag: 801910fd-9b10-4bd3-a396-499a0fffafb6
		summarizeBy: none
		sourceColumn: Descricao

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		lineageTag: 9a9141a1-ee10-4b72-97b4-8eb9bb93a4c3
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Status
		dataType: string
		lineageTag: 3ee5bf0a-6809-4782-8b32-16ecc6631c47
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ValorFluxo
		dataType: double
		lineageTag: c1cd5403-67d4-453e-85f9-2bc8e34ea5bf
		summarizeBy: sum
		sourceColumn: ValorFluxo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FluxoCaixaCompleto = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1JGj93l-FB4TCVMyGFQaNu7_k3_Jz4uFy_7DWUA5dQBY/edit?usp=sharing"),
				    FluxoCaixaCompleto_Table = Source{[name="FluxoCaixaCompleto",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FluxoCaixaCompleto_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DataOriginal", type datetime}, {"DataCompetencia", type datetime}, {"Tipo", type text}, {"Metodo", type text}, {"Conta_Cartao", type text}, {"Categoria", type text}, {"Descricao", type text}, {"Valor", type number}, {"Status", type text}, {"ValorFluxo", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

