table InvestimentoBTC
	lineageTag: 3ea22343-9254-4043-afc2-a09713de1f60

	column DataHora
		dataType: dateTime
		formatString: General Date
		lineageTag: d45526b3-a3a1-4d8b-8611-c7652e6c97f0
		summarizeBy: none
		sourceColumn: DataHora

		variation Variation
			isDefault
			relationship: 937b2997-3448-4a3d-896f-962900f314f5
			defaultHierarchy: LocalDateTable_ab0c4a76-84a9-4782-96b0-51638d2d3b6f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column SaldoBTC
		dataType: double
		lineageTag: 9cf92741-6105-45da-bc95-a799f655568f
		summarizeBy: sum
		sourceColumn: SaldoBTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PrecoBTC
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: baa07e45-34c9-49d7-8461-ccd5064b81a5
		summarizeBy: sum
		sourceColumn: PrecoBTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ValorReais
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: ad96aea4-6628-4d64-9477-235071a1bf09
		summarizeBy: sum
		sourceColumn: ValorReais

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition InvestimentoBTC = m
		mode: import
		source =
				let
				    Fonte = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1JGj93l-FB4TCVMyGFQaNu7_k3_Jz4uFy_7DWUA5dQBY/edit?usp=sharing"),
				    InvestimentoBTC_Table = Fonte{[name="InvestimentoBTC",ItemKind="Table"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(InvestimentoBTC_Table, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"DataHora", type datetime}, {"SaldoBTC", type number}, {"PrecoBTC", Currency.Type}, {"ValorReais", Currency.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

