table InvestimentoCripto
	lineageTag: 340e1aaa-e551-44c3-b2c2-c423dbcc1a03

	column DataHora
		dataType: dateTime
		formatString: General Date
		lineageTag: e2aff263-c511-409d-916e-a3d7b2f965bd
		summarizeBy: none
		sourceColumn: DataHora

		variation Variation
			isDefault
			relationship: c12cecb9-9a66-4860-922d-e3c5853b41af
			defaultHierarchy: LocalDateTable_5f0022ef-a5b6-4ca6-941c-3e2a08c8be47.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Ticker
		dataType: string
		lineageTag: 1e451f5f-c658-493b-9f26-bfe3354c4f83
		summarizeBy: none
		sourceColumn: Ticker

		annotation SummarizationSetBy = Automatic

	column Ativo
		dataType: string
		lineageTag: ede24a40-f24d-45ca-a330-4a30e7318bae
		summarizeBy: none
		sourceColumn: Ativo

		annotation SummarizationSetBy = Automatic

	column SaldoCripto
		dataType: double
		lineageTag: 7bd62cc2-ef8d-4525-9367-37ce7bf010a5
		summarizeBy: sum
		sourceColumn: SaldoCripto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PrecoCripto
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: b814200d-c756-491e-ae9c-457720cf1a6b
		summarizeBy: sum
		sourceColumn: PrecoCripto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ValorReais
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 19c3310e-be88-4522-a348-74fdbcc53978
		summarizeBy: sum
		sourceColumn: ValorReais

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition InvestimentoCripto = m
		mode: import
		source =
				let
				    Fonte = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1JGj93l-FB4TCVMyGFQaNu7_k3_Jz4uFy_7DWUA5dQBY/edit?usp=sharing"),
				    InvestimentoCripto_Table = Fonte{[name="InvestimentoCripto",ItemKind="Table"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(InvestimentoCripto_Table, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"DataHora", type datetime}, {"Ticker", type text}, {"Ativo", type text}, {"SaldoCripto", type number}, {"PrecoCripto", Currency.Type}, {"ValorReais", Currency.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

