table LimitesCategorias
	lineageTag: 3a7e8dbc-b519-471c-b8f1-e7645e527f1d

	column Categoria
		dataType: string
		lineageTag: fcd6ca02-9526-4be5-9517-9710826a85a6
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Limite
		dataType: int64
		formatString: 0
		lineageTag: 3745c2ee-9c4f-4aac-aba8-ed6f24f4413d
		summarizeBy: sum
		sourceColumn: Limite

		annotation SummarizationSetBy = Automatic

	partition LimitesCategorias = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcs7PzUxJVNJRMjY1UIrViVYKTjy8KyUVKGAIFch0y89PAfGNIHyfxKrUIhDfAMIPSy0uKT28sCgzHyhoARELKEotTs0rSS0GCkGNCS3JzAHalIIs5lhcnJmXWFJalFiM0Ouak1pSdHhLXmZyPkjUCGqtZ14Z0KLMXKCx+RDbQfbHAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Categoria = _t, Limite = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Categoria", type text}, {"Limite", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

