name: Rodar Script de Finanças 

on:
  schedule:
    - cron: '0 * * * *'
  
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # upgrade aqui

      - name: Restaurar arquivos de configuração
        env:
          MY_CREDENTIALS: ${{ secrets.CREDENTIALS_JSON }}
          MY_CONFIG: ${{ secrets.CONFIG_PY }}
        run: |
          echo "$MY_CREDENTIALS" > credentials.json
          echo "$MY_CONFIG" > config.py

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar main.py
        run: python main.py
